language: minimal

services:
  - docker

# Set env vars
env:
    global:
      - PROJECT_ID=travis-ci-279121
      - ZONE=europe-west4-a

before_install:
    - gcloud version || true
    - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
    - source /home/travis/google-cloud-sdk/path.bash.inc
    - gcloud version
    - docker build -t zabbix docker/.
    - docker tag zabbix:latest shemetmaksim/zabbix:"$TRAVIS_COMMIT"
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - docker push shemetmaksim/zabbix:"$TRAVIS_COMMIT"
    - echo $CERTS | base64 --decode > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $PROJECT_ID
    - gcloud config set compute/zone $ZONE
    - gcloud compute instances update-container zabbix --zone $ZONE --container-image shemetmaksim/zabbix:"$TRAVIS_COMMIT"
deploy:
    - provider: script
      skip_cleanup: true
      script: deploy.sh
      on:
        branch: master