version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: zabbix
        MYSQL_USER: zabbix
        MYSQL_PASSWORD: password
  bakend:
    build: './backend'
    depends_on:
        - db
    command: zcat create.sql.gz | mysql zabbix -h db -uzabbix -ppassword
  frontend:
    build: './frontend'
    ports:
        - "80:80"
