version: '3'

services:
  db:
    image: mysql:5.6
    command: --character-set-server=utf8 --collation-server=utf8_bin
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: zabbix
        MYSQL_USER: zabbix
        MYSQL_PASSWORD: password
  bakend:
    build: './backend'
    depends_on:
        - db
  frontend:
    build: './frontend'
    ports:
        - "80:80"
